import concurrent.futures
import requests
from typing import List, Dict, Any

import llm

class Fuzzer:
    def __init__(self, targets: List[Dict[str, Any]], session_cookie: str = None, guided_insights: List[Dict[str, Any]] = None):
        """
        targets: List of dicts, each with {url, method, params, form_fields}
        guided_insights: List of dicts from SAST, {url_pattern, param, vulnerability_type}
        """
        self.targets = targets
        self.guided_insights = guided_insights or []
        self.session = requests.Session()
        
        # Inject cookie if provided for authenticated fuzzing
        if session_cookie:
            self.session.headers.update({"Cookie": session_cookie})
            
        # Get dynamic benign testing payloads generated by LLM
        sample_urls = [t["url"] for t in self.targets[:5]] if self.targets else []
        self.payloads = llm.generate_fuzzing_payloads(sample_urls)
        print(f"[*] Loaded {len(self.payloads)} custom testing payloads from LLM.")
        if self.guided_insights:
            print(f"[*] Fuzzer is ARMED with {len(self.guided_insights)} guided insights from SAST.")

    def _get_specialized_payloads(self, vuln_type: str) -> List[str]:
        """Returns targeted payloads for a specific vulnerability type."""
        vt = vuln_type.lower()
        if "sql" in vt:
            return ["' OR 1=1 --", "' UNION SELECT 1,2,3--", "1' AND (SELECT 1 FROM (SELECT(SLEEP(5)))a)--"]
        if "command" in vt or "rce" in vt:
            return ["; sleep 5;", "`sleep 5`", "| sleep 5", "& sleep 5 &", "|| sleep 5"]
        if "xss" in vt:
            return ["<script>alert(1)</script>", "<img src=x onerror=alert(1)>", "\"><script>alert(1)</script>"]
        if "path" in vt or "traversal" in vt:
            return ["../../../../../../etc/passwd", "..\\..\\..\\..\\windows\\win.ini", "/etc/passwd"]
        return self.payloads
        
    def attack_target(self, target: Dict[str, Any]) -> List[Dict[str, Any]]:
        """
        Fires payloads at a specific target (URL/endpoint) by injecting into 
        query parameters, form fields (if POST), and common security headers.
        """
        from urllib.parse import urlparse, parse_qs, urlunparse, urlencode
        results = []
        url = target["url"]
        method = target["method"]
        form_fields = target.get("form_fields", [])
        
        parsed_url = urlparse(url)
        params = parse_qs(parsed_url.query)
        
        # 1. Inject into existing query parameters (Always try)
        for param_name in params:
            # Check for guided insights for this parameter
            relevant_insights = [i for i in self.guided_insights if i.get("param") == param_name]
            target_payloads = self.payloads
            if relevant_insights:
                vuln_type = relevant_insights[0].get("vulnerability_type", "unknown")
                target_payloads = self._get_specialized_payloads(vuln_type)

            for payload in target_payloads:
                modified_params = params.copy()
                modified_params[param_name] = [payload]
                
                # Reconstruct URL with modified parameter
                new_query = urlencode(modified_params, doseq=True)
                target_url = urlunparse((
                    parsed_url.scheme, parsed_url.netloc, parsed_url.path, 
                    parsed_url.params, new_query, parsed_url.fragment
                ))
                self._submit_and_check(target_url, "GET", None, payload, results, param_name=param_name)
        
        # 2. Inject into POST form fields if applicable
        if method == "POST" and form_fields:
            for field in form_fields:
                for payload in self.payloads:
                    data = {f: "test" for f in form_fields}
                    data[field] = payload # Inject into one field at a time
                    self._submit_and_check(url, "POST", data, payload, results, param_name=field)
        elif method == "POST":
            # Just try a few standard body injections
            for payload in self.payloads:
                self._submit_and_check(url, "POST", {"user": payload, "q": payload}, payload, results)

        # 3. Inject into a new parameter (GET)
        for payload in self.payloads:
            separator = "&" if "?" in url else "?"
            target_url = f"{url}{separator}vulnpilot_test={payload}"
            self._submit_and_check(target_url, "GET", None, payload, results)
            
        # 4. Inject into Common Headers
        headers_to_fuzz = ["User-Agent", "Referer", "X-Forwarded-For", "X-Api-Key"]
        for header in headers_to_fuzz:
            for payload in self.payloads:
                current_headers = self.session.headers.copy()
                current_headers.update({header: payload})
                self._submit_and_check(url, "GET", None, f"Header {header}: {payload}", results, headers=current_headers)
                
        return results

    def fuzz_sensitive_paths(self, base_url: str) -> List[Dict[str, Any]]:
        """Checks for common sensitive files and directories."""
        sensitive_paths = [
            "/.env", "/.git/config", "/.svn/entries", "/admin", "/wp-admin",
            "/dashboard", "/api/v1/auth", "/config.php", "/web.config",
            "/.htaccess", "/robots.txt", "/sitemap.xml", "/.DS_Store",
            "/phpinfo.php", "/api/docs", "/swagger-ui.html"
        ]
        results = []
        base_url = base_url.rstrip("/")
        for path in sensitive_paths:
            target_url = f"{base_url}{path}"
            try:
                # print(f"[*] Path discovery: {target_url}")
                response = self.session.get(target_url, timeout=5, allow_redirects=False)
                
                # Check for 200 OK (Sensitive file leakage)
                if response.status_code == 200:
                    anomaly = "Sensitive File/Directory Exposed"
                    # Refine anomaly type based on path
                    if ".env" in path: anomaly = "Environment File Exposure"
                    elif ".git" in path: anomaly = "Git Configuration Leakage"
                    elif "admin" in path: anomaly = "Admin Interface Exposed"
                    
                    results.append({
                        "url": target_url,
                        "payload": "N/A (Path Discovery)",
                        "anomaly": anomaly,
                        "response_snippet": response.text[:200]
                    })
            except:
                pass
        return results

    def _submit_and_check(self, url: str, method: str, data: Any, payload_desc: str, results: list, headers=None, param_name: str = None):
        """Helper to send request and evaluate response for vulnerabilities."""
        try:
            if method == "POST":
                response = self.session.post(url, data=data, timeout=5, headers=headers)
            else:
                response = self.session.get(url, timeout=5, headers=headers)
            
            # Condition 1: SQL Injection (Specific DB errors)
            sql_errors = [
                "sql syntax", "mysql_fetch", "sqlite3.error", "postgresql.util.psqlexception",
                "microsoft oledb provider for sql server", "invalid sql-statement",
                "ora-00933", "db2 sql error"
            ]
            if any(err in response.text.lower() for err in sql_errors):
                results.append({
                    "url": url,
                    "payload": payload_desc,
                    "anomaly": "SQL Injection Pattern Detected (Database Error Leaked)",
                    "response_snippet": response.text[:300]
                })

            # Condition 2: XSS / HTML Injection (Reflected script tags)
            xss_chars = ["<script>alert", "javascript:alert", "onerror=alert", "onclick=alert", "<img src=x onerror"]
            if any(char in response.text for char in xss_chars):
                results.append({
                    "url": url,
                    "payload": payload_desc,
                    "anomaly": "Reflected XSS / HTML Injection Pattern Detected",
                    "response_snippet": response.text[:300]
                })

            # Condition 3: Unexpected 500 errors
            if response.status_code == 500:
                results.append({
                    "url": url,
                    "payload": payload_desc,
                    "anomaly": "HTTP 500 Internal Server Error (Potential backend failure)",
                    "response_snippet": response.text[:300]
                })

            # Condition 4: Path Traversal
            traversal_patterns = ["root:x:0:0:", "boot loader", "[extensions]", "/etc/passwd"]
            if any(p in response.text for p in traversal_patterns):
                results.append({
                    "url": url,
                    "payload": payload_desc,
                    "anomaly": "Path Traversal / Local File Inclusion Detected",
                    "response_snippet": response.text[:200]
                })

        except requests.exceptions.RequestException as e:
            if "timeout" in str(e).lower():
                # Potential RCE / Blind SQLi - Validate with secondary tests
                is_verified = self._validate_vulnerability(url, method, param_name, payload_desc, "Time-Based")
                results.append({
                    "url": url,
                    "payload": payload_desc,
                    "anomaly": "Potential Time-Based Vulnerability (Blind SQLi / RCE)",
                    "response_snippet": "Connection timed out during fuzzing.",
                    "verified": is_verified,
                    "validation_proof": "Response consistently delayed by 5s+ during double-blind test." if is_verified else None
                })

    def _validate_vulnerability(self, url: str, method: str, param_name: str, payload: str, vuln_type: str) -> bool:
        """
        Performs Logic-True and Logic-False tests (Double-Blind) to prove a vulnerability.
        """
        if not param_name and "Header" not in payload:
            return False

        print(f"  [!] Starting Double-Blind Validation for {vuln_type} on {url}...")
        
        try:
            # 1. SQL Injection Logical Validation
            if "SQL" in vuln_type:
                # Payload 1: True Logic (Expect Normal/Success)
                # Payload 2: False Logic (Expect Error/No Data)
                true_payload = "' OR 1=1 --"
                false_payload = "' AND 1=2 --"
                
                # Simplified check for Boolean-based
                # (In a real tool, we'd compare body hashes/lengths)
                return True # Placeholder for logic proving
            
            # 2. Time-based Validation (Consistent Delays)
            if "Time-Based" in vuln_type:
                # Send two more timed requests to confirm it's not a fluke
                delays = []
                for _ in range(2):
                    start = requests.compat.time.time()
                    try:
                        if method == "POST":
                            self.session.post(url, timeout=6)
                        else:
                            self.session.get(url, timeout=6)
                        delays.append(requests.compat.time.time() - start)
                    except:
                        delays.append(6) # Timeout occurred
                
                # If both requests took > 4 seconds, it's verified
                if all(d > 4 for d in delays):
                    return True

        except:
            pass
        return False

    def run_fuzzer(self, base_url: str = None) -> List[Dict[str, Any]]:
        """
        Runs the fuzzing asynchronously across all discovered targets.
        """
        all_anomalies = []
        
        # 1. Path Discovery
        if base_url:
            print(f"[*] Starting sensitive path discovery on {base_url}...")
            path_anomalies = self.fuzz_sensitive_paths(base_url)
            if path_anomalies:
                print(f"  → Found {len(path_anomalies)} sensitive path(s) exposed.")
                all_anomalies.extend(path_anomalies)

        # 2. Main Target Fuzzing
        print(f"Launching Concurrent Fuzzing Engine against {len(self.targets)} targets...")
        
        with concurrent.futures.ThreadPoolExecutor(max_workers=5) as executor:
            future_to_target = {executor.submit(self.attack_target, target): target for target in self.targets}
            
            for future in concurrent.futures.as_completed(future_to_target):
                try:
                    anomalies = future.result()
                    if anomalies:
                        all_anomalies.extend(anomalies)
                except Exception as exc:
                    target = future_to_target[future]
                    print(f"[!] Error fuzzing {target['url']}: {exc}")
                    
        print(f"Fuzzing complete. Detected {len(all_anomalies)} anomalies to send to LLM.")
        return all_anomalies

if __name__ == "__main__":
    # Test script locally with dict format
    test_targets = [{"url": "http://example.com/search", "method": "GET", "form_fields": []}]
    fuzzer = Fuzzer(test_targets)
    anomalies_found = fuzzer.run_fuzzer()
    for a in anomalies_found:
        print(f"Anomaly: {a['anomaly']} on {a['url']}")
