import google.generativeai as genai
import os
import json
from typing import List, Dict, Any

# Configure API Key (Should be pulled from .env in production)
# Ensure you set GOOGLE_API_KEY in your environment variables before running
genai.configure(api_key=os.environ.get("GOOGLE_API_KEY", "AIzaSyC03RYSVQnurGHXX5ZxTxmucTB7p4e-sCw"))

# Using gemini-1.5-flash as it is optimal for fast, structured log analysis
model = genai.GenerativeModel('gemini-1.5-flash')

def generate_fuzzing_payloads(target_urls: List[str]) -> List[str]:
    """
    Uses Gemini to dynamically generate benign testing payloads tailored to the target endpoints.
    """
    prompt = f"""
    You are an expert security engineer building a Dynamic Application Security Testing (DAST) tool.
    I want to fuzz the following application endpoints for vulnerabilities like SQLi, XSS, SSRF, and Path Traversal:
    
    Sample Endpoints:
    {target_urls}
    
    Generate roughly 10 highly effective, **BENIGN** testing payloads. 
    The payloads should be designed to safely trigger database stack traces, 500 internal server errors, or specific reflections without compromising the system.
    Do NOT generate exploits that drop shells or alter data. Use standard benign probes like standard SQLi breakers, XSS tags, null bytes, and traversal paths.
    
    Respond with ONLY a valid JSON Array of strings.
    Example: ["' OR 1=1 --", "<script>alert(1)</script>", "../../../../etc/passwd"]
    Do not use markdown blocks like ```json.
    """
    try:
        print("[*] Asking Gemini to craft custom fuzzing payloads...")
        response = model.generate_content(prompt)
        text = response.text.replace("```json", "").replace("```", "").strip()
        payloads = json.loads(text)
        if isinstance(payloads, list):
            return payloads
    except Exception as e:
        print(f"[!] LLM Payload Generation failed: {e}. Falling back to default payloads.")
        
    # Fallback if API fails
    return [
        "' OR 1=1 --",
        "\" OR 1=1 --",
        "<script>alert('VulnPilot')</script>",
        "../../../../../../../../etc/passwd",
        "`; sleep 3; `",
        "A" * 1500
    ]

def analyze_anomalies(anomalies: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    Takes a list of anomalies from the fuzzer and uses Gemini to analyze them
    and generate safe manual Proofs of Concept.
    """
    analyzed_results = []
    
    if not anomalies:
        return analyzed_results
        
    for anomaly in anomalies:
        prompt = f"""
        You are an expert Cybersecurity Analyst and Penetration Tester.
        Your task is to review the following anomalous HTTP response generated by a Black-Box DAST fuzzer.
        
        Target URL: {anomaly['url']}
        Fuzzing Payload Used: {anomaly['payload']}
        Fuzzer Categorization: {anomaly['anomaly']}
        Server Response Snippet:
        ```
        {anomaly['response_snippet']}
        ```
        
        Please provide a JSON response with the following keys:
        - "vulnerability_type": The likely vulnerability (e.g., SQL Injection, XSS, Path Traversal, Unhandled Exception, etc.).
        - "severity": "Low", "Medium", "High", or "Critical".
        - "explanation": A brief, 2-sentence explanation of why this HTTP response snippet indicates a vulnerability.
        - "manual_poc": A step-by-step, safe, BENIGN proof of concept that the developer can manually execute in their browser or via curl to verify the flaw exists. Do NOT provide an exploit that drops a shell or exfiltrates data. Limit it to safe verifications like triggering syntax errors, alerts, or timed sleeps.

        Respond ONLY in valid JSON format without markdown code block wrappers like ```json .
        """
        
        try:
            print(f"[*] Sending anomaly on {anomaly['url']} to Gemini for Contextual Analysis...")
            response = model.generate_content(prompt)
            
            # Clean possible markdown formatting from json response
            response_text = response.text.replace("```json", "").replace("```", "").strip()
            
            try:
                analysis_json = json.loads(response_text)
            except json.JSONDecodeError:
                # If Gemini fails strict JSON format, fallback gracefully
                print(f"[!] Failed to parse Gemini JSON: {response_text}")
                analysis_json = {
                    "vulnerability_type": "JSON Parsing Error",
                    "severity": "Unknown",
                    "explanation": "Gemini returned invalid JSON format.",
                    "manual_poc": "Review raw logs."
                }
            
            # Merge original anomaly info with LLM analysis
            merged_result = {**anomaly, **analysis_json}
            analyzed_results.append(merged_result)
            
        except Exception as e:
            print(f"[!] Error calling Gemini API: {e}")
            fallback_result = {
                **anomaly, 
                "vulnerability_type": "API Error", 
                "severity": "Unknown", 
                "explanation": "Could not reach Gemini API (Check GOOGLE_API_KEY).", 
                "manual_poc": "N/A"
            }
            analyzed_results.append(fallback_result)
            
    return analyzed_results

def analyze_hybrid(anomalies: List[Dict[str, Any]], code_context: str) -> List[Dict[str, Any]]:
    """
    Synthesizes external fuzzing results with internal source code analysis for modern stack testing.
    """
    if not code_context:
        print("[*] No codebase provided. Falling back to pure DAST (Black-Box) analysis.")
        return analyze_anomalies(anomalies)
        
    print(f"[*] Submitting {len(code_context)} bytes of Source Code + Fuzzing logs to Gemini for Hybrid Analysis...")
    prompt = f"""
    You are an expert Security Engineer conducting a Hybrid Penetration Test (Grey-Box/White-Box).
    You are dealing with a modern framework application (likely React/Next.js/Node).
    
    Here is a snapshot of critical files extracted from the internal Source Code (SAST context):
    [SOURCE CODE START]
    {code_context[:80000]}
    [SOURCE CODE END]
    
    Here are the anomalous HTTP responses generated by our external DAST fuzzer:
    [DAST ANOMALIES START]
    {json.dumps(anomalies, indent=2)}
    [DAST ANOMALIES END]
    
    Task:
    Analyze both the internal source code AND the external fuzzer anomalies (if any).
    1. Check the source code for modern web flaws: Server Action authorization bypasses, exposed secrets in 'getServerSideProps' or API Routes, DOM XSS risks, hardcoded API keys, and vulnerable imports.
    2. Correlate any DAST anomalies with the exact line of code that caused them.
    3. If there are no DAST anomalies, purely analyze the source code and report the flaws found therein.
    
    Respond ONLY with a JSON array of discovered vulnerabilities.
    Format your response EXACTLY like this example:
    [
      {{
        "vulnerability_type": "Data Leak in SSR",
        "severity": "High",
        "url": "Filename or Endpoint",
        "explanation": "The codebase directly returns unfiltered user credentials via SSR.",
        "manual_poc": "Review lines 45 of User.tsx. Remediation: Filter the return object."
      }}
    ]
    Respond purely with the JSON array. Do not use markdown format blocks like ```json.
    """
    
    try:
        response = model.generate_content(prompt)
        text = response.text.replace("```json", "").replace("```", "").strip()
        analysis_json = json.loads(text)
        
        if isinstance(analysis_json, list):
            return analysis_json
        return []
    except Exception as e:
        print(f"[!] Error during Hybrid LLM Analysis: {e}")
        return [{
             "vulnerability_type": "Hybrid Analysis Failed",
             "severity": "Unknown",
             "url": "System",
             "explanation": "LLM failed to process the large codebase context.",
             "manual_poc": "Try reducing the codebase path or checking API limits."
        }]
